name: rider_my
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  fluttertoast: ^8.2.4

  # IMAGE
  cached_network_image: ^3.3.0

  # BASE
  intl: ^0.18.1
  google_fonts: ^6.1.0
  html: ^0.15.4
  shared_preferences: ^2.2.2
  flutter_widget_from_html: ^0.14.6

  # UI
  sliding_up_panel: ^2.0.0+1
  dotted_line: ^3.2.2
  lottie: ^2.7.0
  flutter_rating_bar: ^4.0.1
  flutter_staggered_animations: ^1.1.1
  bottom_picker: ^2.3.2
  country_code_picker: ^3.0.0
  dotted_border: ^2.1.0
  flutter_countdown_timer: ^4.1.0
  timeline_tile: ^2.0.0
  flutter_vector_icons: ^2.0.0

  #OTP TEXTFIELD
  otp_text_field: ^1.1.3

  # MAP
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  google_maps_flutter: ^2.5.0
  flutter_polyline_points: ^2.0.0
  google_maps_place_picker_mb: ^3.1.2

  # IMAGES
  image_picker: ^1.0.4
  file_picker: ^6.1.1

  # CONNECTIVITY
  package_info_plus: ^4.2.0

  # CONNECTIVITY
  http: ^1.1.0
  connectivity_plus: ^5.0.1
  url_launcher: ^6.2.1

  #FIREBASE
  firebase_crashlytics: ^3.4.4
  firebase_core: ^2.32.0
  firebase_auth: ^4.14.0
  firebase_storage: ^11.5.1
  firebase_database: ^10.3.4
  paginate_firestore: ^1.0.3+1
  cloud_firestore: ^4.13.1

  # STATE MANAGEMENT
  mobx: ^2.2.1
  flutter_mobx: ^2.1.1

  # MQTT
  mqtt_client: ^10.0.0

  # Social Login
  google_sign_in: ^6.1.6
  the_apple_sign_in: ^1.1.1

  # DOWNLOAD INVOICE PDF
  pdf: ^3.10.6
  path_provider: ^2.1.1
  open_file: ^3.3.2
  printing: ^5.11.1

  flutter_localizations:
    sdk: flutter

  build_runner: ^2.4.6
  mobx_codegen: ^2.4.0
  location: ^7.0.0
  geolocator_apple: ^2.3.7
  #flutter packages pub run build_runner build --delete-conflicting-outputs

dependency_overrides:
  intl: ^0.18.0
  cloud_firestore: ^4.3.1
  http: ^0.13.0
  chewie: ^1.5.0
  uuid: ^4.0.0
  geolocator_android: 4.1.9

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/flag/
    - images/icons/